name: CI/CD Proxy Cache

on:
  push:
    branches: [ main ]
    paths:
      - 'cloudflare-worker/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'cloudflare-worker/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cloudflare-worker
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: ./cloudflare-worker/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run migrations
      run: npx wrangler d1 migrations apply f1-api-cache-db --env production --remote
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    
    - name: Deploy to Cloudflare Workers
      run: npx wrangler deploy --env production
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}